export const datosExtra = [
    {
      "year_of_occurance": "2005",
      "cci_number": "2005ESPLO001",
      "applicant_country": "españa",
      "name_of_disaster": "Tormenta de Granizo 2005",
      "disaster_type": "Tormenta de granizo",
      "status": "Accepted",
      "first_damage_date": "2005-04-12T00:00:00.000",
      "date_of_initial_application": "2005-05-01T00:00:00.000",
      "time_from_disaster_to": "19",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "530.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "75",
      "eligible_cost_total_damage": "14.20%",
      "paid": "30.140",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    },
    {
      "year_of_occurance": "2006",
      "cci_number": "2006DESSPO001",
      "applicant_country": "alemania",
      "name_of_disaster": "Deslizamiento de tierra 2006",
      "disaster_type": "Deslizamiento de tierra",
      "status": "Accepted",
      "first_damage_date": "2006-08-05T00:00:00.000",
      "date_of_initial_application": "2006-08-20T00:00:00.000",
      "time_from_disaster_to": "15",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "720.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "98",
      "eligible_cost_total_damage": "13.60%",
      "paid": "42.480",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    },
    {
      "year_of_occurance": "2007",
      "cci_number": "2007FRSPO001",
      "applicant_country": "francia",
      "name_of_disaster": "Inundaciones en la Región Central 2007",
      "disaster_type": "Inundaciones",
      "status": "Accepted",
      "first_damage_date": "2007-06-30T00:00:00.000",
      "date_of_initial_application": "2007-07-15T00:00:00.000",
      "time_from_disaster_to": "15",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "320.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "65",
      "eligible_cost_total_damage": "20.30%",
      "paid": "24.800",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    },
    {
      "year_of_occurance": "2008",
      "cci_number": "2008PTSPO001",
      "applicant_country": "portugal",
      "name_of_disaster": "Incendios forestales en Algarve 2008",
      "disaster_type": "Incendios forestales",
      "status": "Accepted",
      "first_damage_date": "2008-07-10T00:00:00.000",
      "date_of_initial_application": "2008-07-20T00:00:00.000",
      "time_from_disaster_to": "10",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "410.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "58",
      "eligible_cost_total_damage": "14.20%",
      "paid": "31.240",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    },
    {
      "year_of_occurance": "2009",
      "cci_number": "2009IT16SPO001",
      "applicant_country": "italia",
      "name_of_disaster": "Erupción volcánica en Sicilia 2009",
      "disaster_type": "Erupción volcánica",
      "status": "Accepted",
      "first_damage_date": "2009-09-14T00:00:00.000",
      "date_of_initial_application": "2009-10-01T00:00:00.000",
      "time_from_disaster_to": "17",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "980.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "140",
      "eligible_cost_total_damage": "14.30%",
      "paid": "54.740",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    },
    {
      "year_of_occurance": "2010",
      "cci_number": "2010UK16SPO001",
      "applicant_country": "reino unido",
      "name_of_disaster": "Inundaciones en Yorkshire 2010",
      "disaster_type": "Inundaciones",
      "status": "Accepted",
      "first_damage_date": "2010-08-01T00:00:00.000",
      "date_of_initial_application": "2010-08-15T00:00:00.000",
      "time_from_disaster_to": "14",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "620.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "85",
      "eligible_cost_total_damage": "13.70%",
      "paid": "39.450",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    },
    {
      "year_of_occurance": "2011",
      "cci_number": "2011GR16SPO001",
      "applicant_country": "grecia",
      "name_of_disaster": "Olas de Calor en Atenas 2011",
      "disaster_type": "Olas de calor",
      "status": "Accepted",
      "first_damage_date": "2011-07-20T00:00:00.000",
      "date_of_initial_application": "2011-08-05T00:00:00.000",
      "time_from_disaster_to": "16",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "350.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "52",
      "eligible_cost_total_damage": "14.80%",
      "paid": "21.756",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    },
    {
      "year_of_occurance": "2012",
      "cci_number": "2012TR16SPO001",
      "applicant_country": "turquía",
      "name_of_disaster": "Terremoto en Anatolia 2012",
      "disaster_type": "Terremoto",
      "status": "Accepted",
      "first_damage_date": "2012-11-24T00:00:00.000",
      "date_of_initial_application": "2012-12-10T00:00:00.000",
      "time_from_disaster_to": "16",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "890.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "105",
      "eligible_cost_total_damage": "11.80%",
      "paid": "47.960",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    },
    {
      "year_of_occurance": "2013",
      "cci_number": "2013CH16SPO001",
      "applicant_country": "suiza",
      "name_of_disaster": "Avalancha en los Alpes 2013",
      "disaster_type": "Avalancha",
      "status": "Accepted",
      "first_damage_date": "2013-02-28T00:00:00.000",
      "date_of_initial_application": "2013-03-15T00:00:00.000",
      "time_from_disaster_to": "15",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "280.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "45",
      "eligible_cost_total_damage": "16.10%",
      "paid": "19.960",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    },
    {
      "year_of_occurance": "2014",
      "cci_number": "2014BESPO001",
      "applicant_country": "bélgica",
      "name_of_disaster": "Inundaciones en Flandes 2014",
      "disaster_type": "Inundaciones",
      "status": "Accepted",
      "first_damage_date": "2014-09-10T00:00:00.000",
      "date_of_initial_application": "2014-09-25T00:00:00.000",
      "time_from_disaster_to": "15",
      "major_regional_neighbouring": "Regional",
      "total_direct_damage_accepted": "440.00",
      "public_damage_eur_million": "",
      "public_total_damage": "",
      "cost_of_eligible_emergency": "62",
      "eligible_cost_total_damage": "14.10%",
      "paid": "35.240",
      "advanced_payment_post_from_twenty_fifteen": "",
      "potential_aid_amount_eur_m_": ""
    }
  ];